#!/usr/bin/env python

import sys
import pycurl
import requests
import json


PY3 = sys.version_info[0] > 2

url = "<http://100.65.132.129:11087/swagger/index.html>"
c = pycurl.Curl()
c.setopt(pycurl.POST, 1)
c.setopt(pycurl.POSTFIELDSIZE, 0)
c.setopt(pycurl.URL, url)
c.setopt(pycurl.HTTPHEADER, ['Accept: application/json',
                             'X-Requested-By:MyClient',
                             'Content-Type:',
                             'Content-Length:',])
c.setopt(pycurl.VERBOSE, 1)
c.setopt(pycurl.USERPWD, "Operator:a")
c.perform

response =

print

